"""empty message

Revision ID: 8b3db3677391
Revises: 972884b20ecb
Create Date: 2020-06-04 20:33:55.700870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b3db3677391'
down_revision = '972884b20ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'created_at')
    op.drop_column('comment', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('updated_at', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('comment', sa.Column('created_at', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
